---
bgp:
  asn: 65511
  router_id: 1.1.1.1
  networks:
    - 10.10.10.0/24
  neighbors:
    - ip_address: 10.10.12.2
      asn: 65512
      name: csr2
    - ip_address: 10.10.13.3
      asn: 65513
      name: csr3
