---
bgp:
  asn: 65512
  router_id: 2.2.2.2
  networks:
    - 10.10.12.0/24
  neighbors:
    - ip_address: 10.10.10.1
      asn: 65511
      name: csr1
    - ip_address: 10.10.13.3
      asn: 65513
      name: csr3