---
- hosts: ios
  name: Generate BGP Configs and push to devices
  gather_facts: false
  vars: 
    config_dir: bgp_configs
  tasks:
    - name: Generate BGP Configs with Jinja2
      template:
        src: "bgp_config.j2"
        dest: "{{ config_dir }}/{{ inventory_hostname }}.cfg"

    - name: Configure BGP on devices using Jinja2
      cisco.ios.ios_config:
        src: "bgp_config.j2"

    - name: Parse output
      ansible.utils.cli_parse:
        command: "show ip bgp summary"
        parser:
          name: ansible.netcommon.ntc_templates
      register: bgp_summary

    - name: Print BGP summary
      ansible.builtin.debug:
        var: bgp_summary['parsed']

    - name: Register necessary variables
      ansible.builtin.set_fact:
        date: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"

    - name: Write report into .csv file
      template:
        src: "bgp_report.j2"
        dest: "reports/report_{{ date }}.csv"
      delegate_to: localhost
      run_once: true

    - name: Assert BGP adjacencies per host are Up
      ansible.builtin.assert:
        that: item['state_pfxrcd'] | lower == "active"
      loop: "{{ bgp_summary['parsed'] }}"
    
    - name: Assert all BGP adjacencies are Up
      ansible.builtin.assert:
        that: 
          - (bgp_summary['parsed']  | selectattr('state_pfxrcd', 'equalto', 'Active') | length) == (bgp_summary['parsed'] | length)
      delegate_to: localhost
      run_once: true

