---
- hosts: ios, eos
  name: Ping checks for reachability
  gather_facts: false
  vars:
    probes_sent: 5
  tasks:

    - name: Ping checks
      napalm.napalm.napalm_ping:
        hostname: "{{ inventory_hostname }}"
        destination: "{{ item }}"
        count: "{{ probes_sent }}"
      loop: "{{ ping_destinations }}"
      register: output

    - name: Register results per ping
      ansible.builtin.set_fact:
        host_results: "{{ host_results|default([]) + [ {
            'dest': item.item,
            'packet_loss': item.ping_results.success.packet_loss,
            'percentage': (1 - item.ping_results.success.packet_loss / probes_sent) * 100
             } ] }}"
      loop: "{{ output['results'] }}"
      ignore_errors: true

    - name: Register necessary variables
      ansible.builtin.set_fact:
        date: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"
    
    - name: Generate csv report
      ansible.builtin.template:
        src: "ping_report.j2"
        dest: "reports/report_{{ date }}.csv"
      delegate_to: localhost
      run_once: true