---
- name: Merge provided config to Cisco NXOS
  cisco.nxos.nxos_vlans:
    config:
      - name: "{{ vlan_name }}"
        vlan_id: "{{ vlan_id }}"
    state: "{{ state }}"
  when: inventory_hostname in groups["nxos"]

- name: Merge provided config to Arista EOS
  arista.eos.eos_vlans:
    config:
      - name: "{{ vlan_name }}"
        vlan_id: "{{ vlan_id }}"
    state: "{{ state }}"
  when: inventory_hostname in groups["eos"]


